### ISSUE TITLE
Error Could not guess image MIME subtype

### ISSUE THREAD

**Issue by opc40772** [Isma399/grafana_mail#1]
Hi, I get this error while running your script.

**Traceback (most recent call last):
  File "./grafana_mail.py", line 127, in <module>
    attach_img(msgRoot, panelId[1])
  File "./grafana_mail.py", line 101, in attach_img
    msgImage = MIMEImage(fp.read())
  File "/usr/lib/python2.7/email/mime/image.py", line 43, in __init__
    raise TypeError('Could not guess image MIME subtype')
TypeError Could not guess image MIME subtype**

Any idea?
Thank's in advance

**Comment by gerhard-tinned** [comment]
Hi, 

Had the same problem. Found a fix and created a [pull request](https://github.com/Isma399/grafana_mail/pull/2) with the fix.

**Comment by gerhard-tinned** [comment]
Apparently the reason is, this does not work without using an API token in the request. This is not implemented as a result all the requests fail.

I Will try to fix this in my fork ... https://github.com/gerhard-tinned/grafana_mail/

**Comment by Isma399** [comment]
Thank you for your fork

**Comment by gerhard-tinned** [comment]
I have added some more improvements if you are interested. 

Related to email headers, rendering the images, ... more to come. :)

**Comment by Isma399** [comment]
Totally interested!

**Comment by gerhard-tinned** [comment]
Check them out in my fork. If you need any explanation or anything, let me know. The highlights as far as I can remember them right now:
* rendering of complete dashboards
* proper email headers to avoid spam detention 
* email text has been added for txt and htm part
* api token command line argument added

Planned:
* override start and end time of the grafh using Grafana syntax
This (from "now-1d/d", to "now-1d/d") would generate what is now. And this would do the same for a monthly graph (from "now-1m/m", to "now-1m/m"). ... and much much more possibilities. 
* reading options from config file. As the api token is quite long, it would make sense to use a config file to store all settings in it.
