### ISSUE TITLE
Does this project support grafana 4.6.1?

### ISSUE THREAD

**Issue by Zhenye-Na** [Isma399/grafana_mail#11]
I saw this project has been updated to support grafana 5, does it still support grafana 4?

Thanks

**Comment by Isma399** [comment]
No, it doesn't.
I've got an old script if you need.
Regards,

**Comment by Zhenye-Na** [comment]
Yes, please!

We are currently using the old grafana v4.6.1 and there is no plan to upgrade it recently. But I really would like to integrate this feature to out usage.

Would you mind share with me?

Thanks!!!

**Comment by Isma399** [comment]
I add the very first script of this project.
I think you'll be able to use it with Grafana4
Regards,

**Comment by Isma399** [comment]
https://github.com/Isma399/grafana_mail/blob/master/grafana4_mail.py
