### ISSUE TITLE
CSV instead of PNG

### ISSUE THREAD

**Issue by jorgemarti** [Isma399/grafana_mail#6]
Hi! I was wondering how difficult would be to make a similar script to send CSV exports of the graphs instead of PNG files. What do you think?

**Comment by Isma399** [comment]
Hi!
how do you want to show graphs with CSV in a mail?
I don't understand.
Thanks

**Comment by jorgemarti** [comment]
Not exactly, the CSV would be included as attachments.  I'm interested in running  an automated monthly generation of CSV exports of the graphs in one of my Dashboards. This is possible from the Grafana web interface (Select graph - More - Export to CSV), but I can't find a way to automate it.

**Comment by Isma399** [comment]
Hello,
maybe you could try with selenium to crawl with javascript until the CSV button.
