### ISSUE TITLE
SyntaxError: invalid syntax On Line 61

### ISSUE THREAD

**Issue by NoelzeN** [Isma399/grafana_mail#8]
Whenever trying to execute the Script I get the following error:

[root@5efd2a549786 grafana_mail]# ./grafana_mail.py -f [Sender] -m [Recipient] -M 172.18.0.1 -G https://grafana.url.com -T XXXX -D 34
  File "./grafana_mail.py", line 61
    print(f"Render complete dashboard with UID {s}")
                                                  ^
SyntaxError: invalid syntax

Dashboard ID is the one I found in the JSON Export of the Dashboard. Any other place where I can verify it? My URL Just has the dashboard's name in it like this:
https:/domain.com/d/NpagFjwik/overview-dashboard?orgId=1
Or would NpagFjwik be the ID then? I expected something numeric. Anyway, also when using NpagFjwik with -D I get the same error. Thanks for any hints

**Comment by Isma399** [comment]
Hello,
what is your Python Version?

**Comment by NoelzeN** [comment]
[root@5efd2a549786 grafana_mail]# python --version
Python 2.7.5

**Comment by Isma399** [comment]
New version is for Python3
Maybe, you could try the old.
I don't know an easy way, but the diff is here:
https://github.com/Isma399/grafana_mail/pull/7/commits/53387d8081b30ba09e296ab9b23771fb85658c29

**Comment by NoelzeN** [comment]
Ok, thanks for the hint. I installed Python 3,6,3 using SCL on CentOS. Now with Python 3 calling **./grafana_mail.py** still gave me the same error while calling **python grafana_mail.py** gave me some new errors. I installed the required modules requests and aiohttp. Now everything works fine. For those coming here with the same issue, the following hints from my side:

1) Install Python 3 to run this script
2) Install modules requests and aiohttp
3) The Dashboard ID indeed is not numeric but the one you can find when you go to the "Share Dashboard" Icon in Grafana. E.g. with the share Link _https://test.url.com/d/NpagFjwik/overview-dashboard?orgId=1&from=1549889921088&to=1550494721088_ the Dashboard ID would be **NpagFjwik**
4) I think Dashboards that contain Text Fields with html content can't be processed completely, at least that widget failed for me

Thanks for the hint to get this resolved
